export { default as Landing } from "./Landing.jsx";
export { default as Men } from "./Men.jsx";
export { default as Women } from "./Women.jsx";
export { default as Kids } from "./Kids.jsx";
export { default as Favorites } from "./Favorites.jsx";
export { default as NotFound } from "./NotFound.jsx";
export { default as Login } from "./Login/index.jsx";
export { default as Registration } from "./Registartion/index.jsx";
export { default as AddCard } from "./AddCard/index.jsx";
