export { default as Landing } from "./Landing/Landing";
export { default as Men } from "./Humans/Men.jsx";
export { default as Women } from "./Humans/Women.jsx";
export { default as Kids } from "./Humans/Kids.jsx";
export { default as Sneaker } from "./CardPages/Sneaker[id]";
export { default as Favorites } from "./Favorites.jsx";
export { default as NotFound } from "./NotFound.jsx";
export { default as Login } from "./Authentication/Login";
export { default as Registration } from "./Authentication/Registration.jsx";
